# Generated by Django 6.0.2 on 2026-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0005_subtask_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_notified_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
